java_binary(
    name = "echo_client",
    srcs = ["EchoClient.java"],
    main_class = "echo.EchoClient",
)

java_binary(
    name = "echo_server",
    srcs = ["EchoServer.java"],
    main_class = "echo.EchoServer",
)

java_binary(
    name = "threaded_echo_server",
    srcs = [
        "ThreadedEchoServer.java",
        "Handler.java",
    ],
    main_class = "echo.ThreadedEchoServer",
)

java_binary(
    name = "bit_ops",
    srcs = ["BitOps.java"],
    main_class = "demo.BitOps",
)

java_binary(
    name = "string_and_byte",
    srcs = ["StringAndByte.java"],
    main_class = "demo.StringAndByte",
)
