java_binary(
    name = "echo_server",
    srcs = ["EchoServer.java"],
    main_class = "echo.EchoServer",
)

java_binary(
    name = "echo_client",
    srcs = ["EchoClient.java"],
    main_class = "echo.EchoClient",
)
