java_binary(
    name = "thread_creation_main",
    srcs = ["ThreadCreationExample.java"],
    main_class = "concurrency.ThreadCreationExample",
)

java_binary(
    name = "thread_termination_main",
    srcs = ["ThreadTerminationExample.java"],
    main_class = "concurrency.ThreadTerminationExample",
)

java_binary(
    name = "thread_join_example",
    srcs = ["ThreadJoinExample.java"],
    main_class = "concurrency.ThreadJoinExample",
)

java_binary(
    name = "race_condition_example",
    srcs = ["RaceConditionExample.java"],
    main_class = "concurrency.RaceConditionExample",
)

java_binary(
    name = "read_write_lock_example",
    srcs = ["ReadWriteLockExample.java"],
    main_class = "concurrency.ReadWriteLockExample",
)
